apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-hosts
data:
  hosts: |
    # Get the IP address of any of the nginx pods in a headless network configuation using
    # kubectl get endpoints APPNAME (which in this case is www)
    # edit it, delete haproxy deployment and redeploy it. 
    10.42.4.60:80 k3s.intranet.local

