apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-cfg
  namespace: default
data:
  syslog-server: "address:stdout, facility:local0, level:info"
  haproxy.cfg: |
    global
      log /dev/log local0 debug

    defaults
      mode http
      timeout connect 5000ms
      timeout client 50000ms
      timeout server 50000ms

    frontend http-in
      bind *:80
      default_backend hello-world

    backend hello-world
      balance roundrobin
      server-template www 3 k3s.intranet.local:80 check
