apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: "rsyslog"
spec:
  storageClassName: store-tmp
  volumeName: data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
