apiVersion: v1
kind: Pod
metadata:
  name: rsyslogsrv1
  namespace: relp-rsyslog
  labels:
    app: relp-rsyslogsrv
spec:
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
    - 10.43.229.169
    searches:
    - intranet.local
  containers:
    - name: rsyslogsrv1
      image: latrina/relp-rsyslog:server
      imagePullPolicy: Always
      ports:
        - containerPort: 22514
          protocol: TCP
      volumeMounts:
        - name: relp-storage
          mountPath: "/var/log"
          readOnly: false
          subPathExpr: "$(POD_UID)"
        - name: config-volume
          mountPath: /etc/rsyslog
        - name: certs-volume
          mountPath: /rsyslog-certs
      env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
      securityContext:
        capabilities:
          add: ["SYSLOG"]
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  volumes:
    - name: relp-storage
      persistentVolumeClaim:
        claimName: relp-storage
    - name: config-volume
      configMap:
        name: rsyslog-config
        items:
          - key: rsyslog.conf
            path: rsyslog.conf
    - name: certs-volume
      configMap:
        name: certs-config
        items:
          - key: ca-cert.pem
            path: ca-cert.pem
          - key: server-cert.pem
            path: server-cert.pem
          - key: server-key.pem
            path: server-key.pem


---

apiVersion: v1
kind: Pod
metadata:
  name: rsyslogsrv2
  namespace: relp-rsyslog
  labels:
    app: relp-rsyslogsrv
spec:
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
    - 10.43.229.169
    searches:
    - intranet.local
  containers:
    - name: rsyslogsrv2
      image: latrina/relp-rsyslog:server
      imagePullPolicy: Always
      ports:
        - containerPort: 22514
          protocol: TCP
      volumeMounts:
        - name: relp-storage
          mountPath: "/var/log"
          readOnly: false
          subPathExpr: "$(POD_UID)"
        - name: config-volume
          mountPath: /etc/rsyslog
        - name: certs-volume
          mountPath: /rsyslog-certs
      env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
      securityContext:
        capabilities:
          add: ["SYSLOG"]
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  volumes:
    - name: relp-storage
      persistentVolumeClaim:
        claimName: relp-storage
    - name: config-volume
      configMap:
        name: rsyslog-config
        items:
          - key: rsyslog.conf
            path: rsyslog.conf
    - name: certs-volume
      configMap:
        name: certs-config
        items:
          - key: ca-cert.pem
            path: ca-cert.pem
          - key: server-cert.pem
            path: server-cert.pem
          - key: server-key.pem
            path: server-key.pem


