apiVersion: v1
kind: Pod
metadata:
  name: rsyslogsrv1
  namespace: relp-rsyslog
  labels:
    app: relp-rsyslogsrv
spec:
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
    - 10.43.229.169
    searches:
    - intranet.local
  containers:
    - name: rsyslogsrv1
      image: latrina/relp-rsyslog:server 
      ports:
        - containerPort: 22514
          protocol: TCP
      volumeMounts:
        - name: relp-storage
          mountPath: "/var/log"
          readOnly: false
          subPathExpr: "$(POD_UID)"
      env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
      securityContext:
        capabilities:
          add: ["SYSLOG"]
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  volumes:
    - name: relp-storage
      persistentVolumeClaim:
        claimName: relp-storage

apiVersion: v1
kind: Pod
metadata:
  name: rsyslogsrv2
  namespace: relp-rsyslog
  labels:
    app: relp-rsyslogsrv
spec:
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
    - 10.43.229.169
    searches:
    - intranet.local
  containers:
    - name: rsyslogsrv2
      image: latrina/relp-rsyslog:server 
      ports:
        - containerPort: 22514
          protocol: TCP
      volumeMounts:
        - name: relp-storage
          mountPath: "/var/log"
          readOnly: false
          subPathExpr: "$(POD_UID)"
      env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
      securityContext:
        capabilities:
          add: ["SYSLOG"]
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  volumes:
    - name: relp-storage
      persistentVolumeClaim:
        claimName: relp-storage
