apiVersion: v1
kind: PersistentVolume
metadata:
  name: relp-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: relp-store 
  hostPath:
    path: /opt/PVs/relp-rsyslog

