apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: relp-storage
  namespace: "relp-rsyslog"
spec:
  storageClassName: relp-store
  volumeName: relp-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

