apiVersion: v1
kind: Service
metadata:
  name: "relp-svc"
  namespace: "relp-rsyslog"
spec:
  ports:
    - port: 22514
      targetPort: 22514
      protocol: TCP
  type: NodePort
  selector:
    app: "relp-rsyslogsrv"
