---
apiVersion: v1
kind: Namespace
metadata:
  name: debug

---
apiVersion: v1
kind: Service
metadata:
  name: pod # must match subdomain
  namespace: debug
spec:
  clusterIP: None
  selector:
    app: dnsutils # must match pod labels

---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: dnsutils
  namespace: debug
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dnsutils
  template:
    metadata:
      labels:
        app: dnsutils
    spec:
      subdomain: pod
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 10.43.141.15 # CoreDNS's svc cluster IP
        searches:
        - debug.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        - intranet.local
      containers:
      - name: dnsutils
        image: registry.k8s.io/e2e-test-images/agnhost:2.39
        command: ["sleep", "infinity"]
        imagePullPolicy: IfNotPresent
