apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-udp-config
  namespace: wireguard
data:
  nginx.conf: |
    worker_processes 1;
    events {}
    stream {
      resolver 10.43.141.15 valid=10s ipv6=off;
      upstream wireguard {
        zone wireguard 64k;
        hash $remote_addr consistent;
        server wireguard-0.wireguard.wireguard.svc.cluster.local:51820 resolve;
        server wireguard-1.wireguard.wireguard.svc.cluster.local:51820 resolve;
        server wireguard-2.wireguard.wireguard.svc.cluster.local:51820 resolve;
      }
      server {
        listen 51820 udp;
        proxy_pass wireguard;
        proxy_timeout 30s;
        proxy_responses 1;
      }
    }
