apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-providers
  namespace: monitoring
data:
  providers.yaml: |+
    apiVersion: 1
    providers:
    - name: 'default'
      ordId: 1
      folder: ''
      type: file
      options:
        path: /etc/grafana/dashboards
