apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rsyslogclt
  namespace: relp-rsyslog
spec:
  serviceName: "relp-clt-svc"
  replicas: 2
  selector:
    matchLabels:
      app: relp-rsyslogclt
  template:
    metadata:
      labels:
        app: relp-rsyslogclt
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 10.43.229.169
        searches:
        - intranet.local
      containers:
        - name: rsyslogclt
          image: latrina/relp-rsyslog:client
          imagePullPolicy: Always
          volumeMounts:
            - name: ctl-certs-volume
              mountPath: /rsyslog-certs
          env:
            - name: TZ
              value: Europe/London
            - name: RSYSLOGSRV_CENTRAL
              value: rsyslogsrv1.relp-svc.relp-rsyslog.svc.intranet.local
            - name: RSYSLOGSRV_SECONDARY
              value: rsyslogsrv2.relp-svc.relp-rsyslog.svc.intranet.local
          securityContext:
            capabilities:
              add: ["SYSLOG"]
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: ctl-certs-volume
          configMap:
            name: ctl-certs-config
            items:
              - key: ca-cert.pem
                path: ca-cert.pem
              - key: client-cert.pem
                path: client-cert.pem
              - key: client-key.pem
                path: client-key.pem
