apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
---
apiVersion: v1
kind: Secret
metadata:
  name: wg-privatekey
  namespace: wireguard
type: Opaque
stringData:
  privatekey: "QGYtRyvm9NlG8gZsQb6AdCTQRtRJQDj1D3WXjcgmRlY="
