apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: wireguard
spec:
  type: ClusterIP
  clusterIP: 10.43.10.0
  selector:
    app: wireguard
  ports:
  - port: 51820
    targetPort: 51820
    protocol: UDP
