# Allow Prometheus to discover service endpoints
apiVersion: v1
kind: Service
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    k8s-app: kube-controller-manager
  ports:
    - name: metrics
      protocol: TCP
      port: 10257
      targetPort: 10257
