# Allow Prometheus to discover service endpoints
apiVersion: v1
kind: Service
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    k8s-app: kube-scheduler
  ports:
    - name: metrics
      protocol: TCP
      port: 10259
      targetPort: 10259
