apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <body>
      <h1>Hello World!</h1>
    </head>
    </body>
    </html>

